version: '3.8'
services:
  web:
    image: darrentiang0/esmos-odoo:latest
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - "8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=214Odoo

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=214Odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs

volumes:
  odoo-web-data:
  odoo-db-data: